### ISSUE TITLE
Panic when iterating through FDs

### ISSUE THREAD

**Issue by alisle** [eminence/procfs#18]
I am getting a panic when I try and extract the fd from a particular process, the code I am running is:
```
if let Result::Ok(fds) = process.fd() {
   for fd in fds {
      if let FDTarget::Socket(inode) = fd.target {
         map.insert(inode, process.pid());
       }
  }
}
```

The exception I am getting is 

```
hread 'main' panicked at 'attempt to subtract with overflow', /home/alisle/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.4.1/src/process.rs:984:63
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: <procfs::process::FDTarget as core::str::FromStr>::from_str
             at /home/alisle/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.4.1/src/process.rs:984
  10: procfs::process::Process::fd
             at /home/alisle/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.4.1/src/process.rs:1369
  11: zerotrust_track::proc::Proc::update
             at src/proc/mod.rs:43
  12: zerotrust_track::proc::Proc::new
             at src/proc/mod.rs:32
  13: zerotrust_track::parser::Parser::new
```

The process that it is hanging up on has the following FDs:
```
root@sleepy:/proc/1149/fd# ls -al
total 0
dr-x------ 2 root root  0 Jan 16 09:43 .
dr-xr-xr-x 9 root root  0 Jan 16 09:43 ..
lr-x------ 1 root root 64 Jan 16 09:43 0 -> /dev/null
lrwx------ 1 root root 64 Jan 16 09:43 1 -> 'socket:[22188]'
lr-x------ 1 root root 64 Jan 16 09:43 10 -> /sys/devices/platform/dell-laptop/leds/dell::kbd_backlight/brightness_hw_changed
lr-x------ 1 root root 64 Jan 16 09:43 11 -> /dev/input/event0
lrwx------ 1 root root 64 Jan 16 09:43 12 -> 'socket:[31154]'
lrwx------ 1 root root 64 Jan 16 09:43 2 -> 'socket:[22188]'
lrwx------ 1 root root 64 Jan 16 09:43 3 -> 'anon_inode:[eventfd]'
lrwx------ 1 root root 64 Jan 16 09:43 4 -> 'anon_inode:[eventfd]'
lrwx------ 1 root root 64 Jan 16 09:43 5 -> 'socket:[28263]'
lrwx------ 1 root root 64 Jan 16 09:43 6 -> 'anon_inode:[eventfd]'
l-wx------ 1 root root 64 Jan 16 09:43 7 -> /run/systemd/inhibit/4.ref
lrwx------ 1 root root 64 Jan 16 09:43 8 -> 'socket:[22198]'
lrwx------ 1 root root 64 Jan 16 09:43 9 -> /sys/devices/platform/dell-laptop/leds/dell::kbd_backlight/brightness
root@sleepy:/proc/1149/fd# 
```
I am running ubuntu 18.04 on a Dell XPS 15, the process which is causing the issues is /usr/lib/upower/upowerd 

I am using 0.4.1 version of the crate.

**Comment by alisle** [comment]
The issue seems to be the 
```/sys/devices/platform/dell-laptop/leds/dell::kbd_backlight/brightness```

The FDTarget FromStr is using `s.contains(':')` to filter the fds, unfortunately because of the :: this line isn't filtered causing `let inode = expect!(s.next(), "other inode");` to fail

**Comment by eminence** [comment]
Ahh, very interesting.  Thanks for the bug report!  I think the thing to do here is to first check if the target starts with a forward slash.  If so, assume that it's a path and don't try to split on colon.   I'll work up a fix

**Comment by eminence** [comment]
I pushed a fix for this.  Before I publish a new version to crates.io, do you think you could give the latest version a test?

**Comment by alisle** [comment]
Sure, I will give it a go.

**Comment by alisle** [comment]
OK I have tested the new code and it works great!

**Comment by eminence** [comment]
Thanks for testing!  I've just published this fix on crates.io as v0.4.2
