### ISSUE TITLE
Panic: Failed to unwrap line (Failed to read line)

### ISSUE THREAD

**Issue by dbrgn** [eminence/procfs#33]
Steps to reproduce on my system:

```
$ cargo install procs
$ procs

thread 'main' panicked at 'Failed to unwrap line (Failed to read line). Please report this as a procfs bug.', /home/danilo/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.4.7/src/process.rs:910:24
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: procfs::process::Process::io
   8: procs::run_default
   9: procs::run
  10: procs::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: main
  16: __libc_start_main
  17: _start
```

[procs](https://github.com/dalance/procs) still uses version 0.4.7, but I didn't see an obvious fix in your git commit log.

CC @dalance.

**Comment by dalance** [comment]
I think this issue was fixed by https://github.com/eminence/procfs/pull/27.
But I forgot to update procfs.
I'll release procs with procfs v0.5.0.

**Comment by eminence** [comment]
@dalance thanks!   I can also reproduce this on my machine, so let me know if you want me to test a new version of `procs`.

**Comment by dalance** [comment]
I released procs v0.8.2. Could you try it?

**Comment by dbrgn** [comment]
Yep, works now for me! :slightly_smiling_face: Thanks for the quick fix.

**Comment by dalance** [comment]
Thanks!
